development:
  host: localhost
  database: pincool_development

test:
  host: localhost
  database: pincool_test

production:
  hosts: 
    - - localhost
      - 27017
    - - localhost
      - 27018
  database: pincool_production
