development:
  sessions:
    default:
      database: pincool_development
      hosts: 
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: pincool_test
      hosts: 
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: pincool_production
      hosts: 
        - localhost:27017
  options:
    raise_not_found_error: false

