development:
  host: localhost
  database: pincool_development

test:
  host: localhost
  database: pincool_test

# set these environment variables on your prod server
production:
  host: 
    - - localhost
      - 27017
    - - localhost
      - 27018
  database: pincool_production
  
